# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Name

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fe0597ed50d548df92c682f9cda9919a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_87f7c3ce1059464792fbebd25205fa6d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_fe0597ed50d548df92c682f9cda9919a }}/pappzsombor/azure-webapp-test:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Name'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9d727176227749e3b21af6476a8e64f9 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_fe0597ed50d548df92c682f9cda9919a }}/pappzsombor/azure-webapp-test:${{ github.sha }}'
